### ISSUE TITLE
Уточнение по проекту

### ISSUE THREAD

**Issue by DisloyalSnow911** [DivanX10/Smart-Air-Freshener-with-Balloon-Detection#1]
Здравствуйте, хотел уточнить пару моментов по проекту:
1. Возможна ли работа освежителя без платформы на 3D принтере? Можно ли её заменить на что-то подходящее, если нет принтера под рукой?
2. Как освежитель понимает какой балон вставлен - для каждого балона есть свой номинал резистора? При установке он замыкает резистором дугу и круг (A0 и +3.3)? На скриншотах плохо видно где установлены концы проводов. Есть ли список номиналов для разных балонов?
3. Подскажите по подключению понижающего преобразователя напряжения  - он подключается к +3.3 и GND на ESP? На скриншотах не видно этих проводов + на одном скриншоте от понижайки идут провода одного цвета, а на другом другие. При напряжении 2.2В ESP работает?
4. Подскажите к какому месту на родной плате подключается резистор на 1кОм?

Проект впечатляющий! Если довести документацию по подключению и схемам до ума, он станет просто бесценным.

**Comment by DivanX10** [comment]
**Возможна ли работа освежителя без платформы на 3D принтере? Можно ли её заменить на что-то подходящее, если нет принтера под рукой?**


Платформа необязательна, но вам нужно придумать что-то такое, чтобы можно было измерить резистор на сопротивление, аналог мультиметра.

![Image](https://github.com/user-attachments/assets/b241e021-df2b-48b0-9cd4-21b4e8220435)

----

**Как освежитель понимает какой баллон вставлен - для каждого баллона есть свой номинал резистора?** 


С помощью измерения сопротивления резистора можно определить конкретный баллон. Например, резисторы имеют номиналы: 100 кОм, 220 кОм, 300 кОм, 470 кОм, 680 кОм, а ESP измеряет сопротивление подключенного резистора и отображает это в сенсоре. Далее в коде делаем условие. Если измеренное сопротивление находится в диапазоне 90–120 кОм, а в коде есть условие диапазона 80-140 кОм, то определяется "Баллон 1", если измеренное сопротивление находится в диапазоне 200–240 кОм, а в коде есть условие диапазона 180-260 кОм, то определяется "Баллон 2" и т.д. Такой подход с использованием различных номиналов резисторов позволяет точно идентифицировать каждый баллон благодаря достаточному разбросу значений сопротивлений.

----
**Есть ли список номиналов для разных баллонов?**

В озоне купите [этот набор](https://ozon.ru/t/nkShRsg) и используйте резисторы, например: 1кОм, 20кОм, 47кОм, 100кОм, 300кОм, 680кОм
![Image](https://github.com/user-attachments/assets/00b03f4d-918d-461c-81ce-5e9a4174d667)

----
**При установке он замыкает резистором дугу и круг (A0 и +3.3)?**

Подробности можете прочитать на официальном сайте ESPHome в разделе Resistance Sensor. [Ссылка на Resistance Sensor](https://esphome.io/components/sensor/resistance.html)

Есть распиновка Wemos D1 mini где видны контакты A0 и +3.3. На плате они так и обозначены
![Image](https://github.com/user-attachments/assets/78f275ad-dbb5-404c-889a-20f4563e91b9)

----

**Подскажите по подключению понижающего преобразователя напряжения - он подключается к +3.3 и GND на ESP? На скриншотах не видно этих проводов + на одном скриншоте от понижайки идут провода одного цвета, а на другом другие. При напряжении 2.2В ESP работает?**

Нарисовал схему, надеюсь, что не ошибся, уже прошло много времени и я забыл что и как. Подправьте меня, если найдете ошибку.

![Image](https://github.com/user-attachments/assets/b3cfcb0e-4f7a-46c0-831c-ff5567b6be6e)

**Comment by DisloyalSnow911** [comment]
Спасибо за ответ, осталось ещё парочка вопросов 
- На схеме плохо видно куда на родной плате подключается резистор на 1кОм (зеленый провод)
- При замене на 5.1 кОм для A0 - в конфигурации тоже обязательно править на 5.1 кОм?
- А output разве не синий провод (GND)?
- Обрезать дорожку только одну крайнюю (та, что ближе к отверстию на середине?
- Рычаг на 3.3В хорошо работал?

**Comment by DivanX10** [comment]
**На схеме плохо видно куда на родной плате подключается резистор на 1кОм (зеленый провод)**
Один конец резистора к контакту "МИНУС", а второй конец к первой ножке микросхемы(смотрите на точку)
![Image](https://github.com/user-attachments/assets/7f7bafd0-1d9a-4a9e-b155-58178315a85f)

**При замене на 5.1 кОм для A0 - в конфигурации тоже обязательно править на 5.1 кОм?**
Обязательно. Указываете в коде тот номинал, как у резистора, в противном случае измерение будет ошибочным.

**А output разве не синий провод (GND)?**
Цвет провода не имеет значения, главное контакты куда припаиваются провода. Я их обозначил для понимания куда нужно паять

**Обрезать дорожку только одну крайнюю (та, что ближе к отверстию на середине?**
Режете дорожку от 6 ножки микросхемы или от желтого провода как на фото. желтый провод припаян к 6 ножке 
![Image](https://github.com/user-attachments/assets/3e7cbddf-8711-40cd-a4a4-c92fa072e982)

Фото без линии. Обратите внимание как дорожка перерезана
![Image](https://github.com/user-attachments/assets/4d1fb911-8ba2-43b3-b708-25842c869f6c)


**Рычаг на 3.3В хорошо работал?**
На 3,3В рычаг очень сильно давил на клапан, что приводило к прокручиванию шестерней и издавал громкий треск. Так можно сломать зубья у шестерней. Нужно найти то напряжение, где при нажатии на клапан, шестерне не будут трещать, а будет работать как из коробки.

**Comment by DisloyalSnow911** [comment]
Спасибо за уточнения, обязательно попробую повторить Ваш проект.

**Comment by DisloyalSnow911** [comment]
Здравствуйте, попытался повторить Ваш проект, но пока столкнулся с проблемой. Симптомы: при нажатии через веб-интерфейс "пшика" не происходит. 

Плата управления немного поменялась (Рис. 2), но я нашёл дорожку от 6-й ноги и обрезал её.
Проверял напряжения: питаюсь от 5 В, далее вход MP1584EN (с этого входа провода на ESP – работает корректно). На входе MP1584EN – 5 В, на выходе 3,2 В (подключаюсь к плате управления, коричневый и оранжевый провод - Рис. 1). На самих контактах на плате управления примерно 2,6–2,8 В.
Все провода звонятся, кроме земли между MP1584EN и платой управления (возможно, как-то мешает измерить резистор на 1 кОм).
Подскажите, где что проверить?
Также есть несколько вопросов:
- физическая кнопка сверху должна при этом работать?
- в каком положении должен находиться таймер для работы ESP? (OFF, 9, 18, 36)
- всё-таки куда на Вашей схеме подключен синий провод GND? Быть может, не спроста он подключен не к минусу батареек?
- при отсутствующем баллоне кнопка распыления будет работать? (Вешал 100 кОм резистор при 5,1 кОм на ESP – показывал: "Пион и сочные ягоды")
- какие симптомы будут, если не обрезать 6 дорожку?
Надеюсь на Вашу помощь
![Image](https://github.com/user-attachments/assets/4c08df10-d2d8-4ed5-b3f5-b6c68947bada)
![Image](https://github.com/user-attachments/assets/8648961b-a531-40c1-a351-6ef62464f66c)
<img width="2544" height="976" alt="Image" src="https://github.com/user-attachments/assets/ad6ecd7d-be66-4792-8373-fffcd0f5f8c5" />

**Comment by DivanX10** [comment]
1) Да, физическая кнопка должна работать. При нажатии на физическую кнопку в ESPHome в бинарном сенсоре вы должны увидеть, что вы нажали на кнопку. Также должно работать и с ESPHome.

2) Рычажок должен стоять строго в положении OFF, в других положениях работать не будет. Мы в плате врезаемся в режим OFF и управляем нажатием дистанционно, а другое положение таймера блокирует удаленное управление

3) Отсутствие баллона не должно влиять на нажатие кнопки, это может работать и без баллона. Эта блокировка работает для автоматизации, но если решитесь нажать вручную, то должно работать. 

4) Если не обрезать дорожку, то вы не сможете дистанционно нажимать на кнопку.

5) Я прежде, чем нарисовать вам схему, разобрал свой освежитель воздуха и достал плату. Ошибка исключена. 

6) У вас другая плата. Я не смогу вам помочь, поскольку не являюсь электронщиком и не разбираюсь в принципах работы. У меня есть освежитель воздуха на Zigbee, который я приобрёл в чате SLS Zigbee в телеграм. Я захотел переделать освежитель, но не стал извлекать контроллер Zigbee и решил сохранить всё как есть. В итоге я купил второй, точно такой же, там была точно такая же плата. Я успешно скопировал схему подключения и встроил ESP. Если вы посмотрите на мою плату, то увидите, что дорожка проходит через резистор, а затем обратите на конечный путь. У вас всё иначе.

Плата слева — это моя, плата справа — это ваша.
![Image](https://github.com/user-attachments/assets/2795fa3e-c71d-498d-882d-eb02973fc951)

**Comment by DivanX10** [comment]
У меня сейчас не работает определение баллона. Контакты из-за влажности отсырели и потеряли проводимость тока. Мне лень всё восстанавливать, в итоге добавил условие, чтобы исключить условие проверки наличия баллона и определение баллона.

```
      - if:
          condition:
            - lambda: |-
                return int(x) < 30 and id(idIgnoreBalloon).state == true;
          then:
            - text_sensor.template.publish:
                id: ballon
                state: "Любой аромат"
```


Добавил выключатель Игнорировать баллон
```
switch:
#Игнорировать баллон?
  - platform: template
    name: Ignore balloon
    icon: mdi:spray
    id: idIgnoreBalloon
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
```



Вот полный код для примера


```
#####################################################################################
##################################### Переменные ####################################
substitutions:
  board_name: Glade Air Freshener
  node_name: airfreshener_glade

#####################################################################################
################################ Основная конфигурация ##############################
esphome:
  name: ${node_name}
  friendly_name: Glade Air Freshener
  comment: WeMos D1 Mini Air Freshener

#####################################################################################
###################################### Платформа ####################################
esp8266:
  board: d1_mini
  framework:
    version: 3.1.2 #recommended
  restore_from_flash: true #Сохраняем предустановленные настройки. После перезагрузки настройки не сбрасываются

#Поскольку все устройства имеют ограниченное количество циклов записи на флэш-память, эта настройка помогает сократить количество операций записи на флэш-память из-за быстрой смены компонентов. 
#В прошлом, когда изменялись такие компоненты, как light, switch, fan и globals, состояние немедленно фиксировалось для flash. Результатом этого стало то, что последнее состояние этих компонентов 
#всегда будет восстанавливаться до своего последнего состояния при отключении питания, однако это может привести к потенциально быстрому повреждению флэш-памяти при быстрой замене этих компонентов.
#Таким образом, была реализована функция безопасности для устранения проблем, возникающих в результате ограниченного числа циклов записи на флэш-память. Состояние сначала сохраняется в памяти, а затем 
#сбрасывается на флэш-память по истечении flash_write_interval времени. Это приводит к меньшему количеству операций записи на флэш-память, сохраняя работоспособность флэш-памяти.
#Сброс данных на флэш-накопитель для уменьшения износа флеш-накопителя
preferences:
  flash_write_interval: 1min

#####################################################################################
################################ Wi-Fi и точка доступа ##############################
#Учетные данные Wi-Fi для подключения платы к домашней сети
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  reboot_timeout: 15min
  enable_on_boot: true
  passive_scan: false

#Если не будет связи с WiFi, то поднимется точка доступа
  ap:
    ssid: ESP AirFreshener Glade
    password: !secret ap_esp_password
    ap_timeout: 1 min
    manual_ip:
      static_ip: 192.168.4.1
      gateway: 192.168.4.1
      subnet: 255.255.255.0

#Компонент captive portal в ESPHome является резервным механизмом на случай сбоя подключения к настроенному Wi-Fi.
captive_portal:

#Веб сервер
web_server:
  port: 80

#Журналирование
logger:
  level: ERROR

#Обновление по воздуху (OTA)
ota:
  - platform: esphome
    id: idOTA
    password: !secret ota


#Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

#####################################################################################
####################################### Скрипт ######################################
script:
  - id: id_ballon_counter
    then:
      - if:
          condition:
            lambda: |-
              return id(resistance_sensor).state > 50 and id(resistance_sensor).state < 100;
          then:
            - number.increment:
                id: id_counter_aroma_ballon_01 #Пион и сочные ягоды
                cycle: false
      - if:
          condition:
            lambda: |-
              return id(resistance_sensor).state > 190 and id(resistance_sensor).state < 250;
          then:
            - number.increment:
                id: id_counter_aroma_ballon_02 #Океанский оазис
                cycle: false
      - if:
          condition:
            lambda: |-
              return id(resistance_sensor).state > 500 and id(resistance_sensor).state < 650;
          then:
            - number.increment:
                id: id_counter_aroma_ballon_03 #Свежесть белья
                cycle: false
      - if:
          condition:
            lambda: |-
              return id(resistance_sensor).state > 1100 and id(resistance_sensor).state < 1300;
          then:
            - number.increment:
                id: id_counter_aroma_ballon_04 #Свежесть утра
                cycle: false
      - if:
          condition:
            lambda: |-
              return id(resistance_sensor).state > 1800;
          then:
            - number.increment:
                id: id_counter_aroma_ballon_05 #Японский сад
                cycle: false

#####################################################################################
################################## Сенсор ###########################################
sensor:
#Сенсор уровня сигнала WiFi
  - platform: wifi_signal
    name: RSSI WiFi
    icon: mdi:wifi
    update_interval: 60s

#Скрытый сенсор безотказной работы в секундах
  - platform: uptime
    name: Uptime sec
    icon: mdi:clock-outline
    id: uptime_sensor
    internal: True #Скрыть - true \показать - false
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_esp
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (String(minutes) + "m")
              ).c_str();

#Скрытый служебный сенсор нажатия на кнопку
  - platform: template
    name: Click Spray
    id: sensor_spray
    internal: True #Скрыть - true \показать - false

#Датчик сопротивления для замера сопротивдения и определения баллона
#Компонент Analog To Digital Sensor
  - platform: adc
    pin: A0
    id: source_sensor
    name: ADS
    update_interval: 1s
  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: 5.1kOhm
    reference_voltage: 3.3v
    name: Resistance
    on_value:
      - if:
          condition:
            - lambda: |-
                return int(x) < 30 and id(idIgnoreBalloon).state == false;
          then:
            - text_sensor.template.publish:
                id: ballon
                state: "Баллон извлечен"
      - if:
          condition:
            - lambda: |-
                return int(x) < 30 and id(idIgnoreBalloon).state == true;
          then:
            - text_sensor.template.publish:
                id: ballon
                state: "Любой аромат"
      - if:
          condition:
            - lambda: |-
                return int(x) > 50 and int(x) < 120;
          then:
            - text_sensor.template.publish:
                id: ballon
                state: "Пион и сочные ягоды"
      - if:
          condition:
            - lambda: |-
                return int(x) > 190 and int(x) < 250;
          then:
            - text_sensor.template.publish:
                id: ballon
                state: "Океанский оазис"
      - if:
          condition:
            - lambda: |-
                return int(x) > 500 and int(x) < 650;
          then:
            - text_sensor.template.publish:
                id: ballon
                state: "Свежесть белья"
      - if:
          condition:
            - lambda: |-
                return int(x) > 1100 and int(x) < 1300;
          then:
            - text_sensor.template.publish:
                id: ballon
                state: "Свежесть утра"
      - if:
          condition:
            - lambda: |-
                return int(x) > 1800;
          then:
            - text_sensor.template.publish:
                id: ballon
                state: "Японский сад"


#####################################################################################
################################## Бинарный сенсор ##################################
binary_sensor:
#Скрытый служебный бинарный сенсор нажатия на кнопку, который при смене статуса вкл\выкл выключатель для распыления
  - platform: gpio
    pin: GPIO13
    name: Spray Button Press
    internal: True #Скрыть - true \показать - false
    id: button_sensor_d7
    on_press:
      then:
        - switch.turn_on: switch_spray
        - delay: 5s
        - switch.turn_off: switch_spray

#Видимый бинарный сенсор для отображения статуса, это может пригодиться в автоматизации HomeAssistant
  - platform: template
    name: Status Spray
    icon: mdi:spray
    id: switch_state
    internal: false #Скрыть - true \показать - false
    lambda: |-
      if (id(switch_spray).state) {
        return true;
      } else {
        return false;
      }


#####################################################################################
################################## Выключатель ######################################
#Скрытый служебный выключатель для распыления
switch:
  - platform: gpio
    pin: GPIO15
    name: Single Click Spray
    internal: True #Скрыть - true \показать - false
    id: switch_spray
    icon: mdi:spray
    restore_mode: ALWAYS_OFF
    on_turn_on:
      then:  
        - number.set:
            id: id_general_counter
            value: !lambda |-
              return ((id(id_general_counter).state)+1);
        - sensor.template.publish:
            id: sensor_spray
            state: !lambda return id(switch_spray).state;
        - component.update: id_general_counter
        - delay: 10s
        - switch.turn_off: switch_spray
        - sensor.template.publish:
            id: sensor_spray
            state: !lambda return id(switch_spray).state;
        - script.execute: id_ballon_counter

#Игнорировать баллон?
  - platform: template
    name: Ignore balloon
    icon: mdi:spray
    id: idIgnoreBalloon
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON


#####################################################################################
####################################### Число #######################################
#Счетчик распылении
number:
#Счетчик ресурса освежителя воздуха
  - platform: template
    name: General counter #Общий счетчик
    icon: mdi:counter
    id: id_general_counter
    restore_value: true
    update_interval: 30s
    min_value: 0
    max_value: 9999999999999
    mode: box #slider/box
    step: 1
    optimistic: true

#Счетчик ресурса баллона 01 (если сменили название аромата баллона, то указываем только имя баллона для которого ведется учет, например Peony and juicy berries или Freshness of linen)
  - platform: template
    name: 'Counter: Peony and juicy berries' #Пион и сочные ягоды
    icon: mdi:counter
    id: id_counter_aroma_ballon_01
    restore_value: true
    update_interval: 30s
    min_value: 0
    max_value: 3000
    mode: box #slider/box
    step: 1
    optimistic: true

#Счетчик ресурса баллона 02 (если сменили название аромата баллона, то указываем только имя баллона для которого ведется учет, например Peony and juicy berries или Freshness of linen)
  - platform: template
    name: 'Counter: Ocean Oasis' #Океанский оазис
    icon: mdi:counter
    id: id_counter_aroma_ballon_02
    restore_value: true
    update_interval: 30s
    min_value: 0
    max_value: 3000
    mode: box #slider/box
    step: 1
    optimistic: true

#Счетчик ресурса баллона 03 (если сменили название аромата баллона, то указываем только имя баллона для которого ведется учет, например Peony and juicy berries или Freshness of linen)
  - platform: template
    name: 'Counter: Freshness of linen' #Свежесть белья
    icon: mdi:counter
    id: id_counter_aroma_ballon_03
    restore_value: true
    update_interval: 30s
    min_value: 0
    max_value: 3000
    mode: box #slider/box
    step: 1
    optimistic: true

#Счетчик ресурса баллона 04 (если сменили название аромата баллона, то указываем только имя баллона для которого ведется учет, например Peony and juicy berries или Freshness of linen)
  - platform: template
    name: 'Counter: Freshness of the morning' #Свежесть утра
    icon: mdi:counter
    id: id_counter_aroma_ballon_04
    restore_value: true
    update_interval: 30s
    min_value: 0
    max_value: 3000
    mode: box #slider/box
    step: 1
    optimistic: true

#Счетчик ресурса баллона 05 (если сменили название аромата баллона, то указываем только имя баллона для которого ведется учет, например Peony and juicy berries или Freshness of linen)
  - platform: template
    name: 'Counter: Japanese Garden' #Японский сад
    icon: mdi:counter
    id: id_counter_aroma_ballon_05
    restore_value: true
    update_interval: 30s
    min_value: 0
    max_value: 3000
    mode: box #slider/box
    step: 1
    optimistic: true


#####################################################################################
####################################### Кнопка ######################################
button:
#Перезагрузка
  - platform: restart
    name: Restart
    icon: mdi:restart

#Распылить
  - platform: template
    name: Click Spray
    icon: mdi:spray
    on_press:
      then:  
       - switch.turn_on: switch_spray

#Сбросить счетчик для баллона 01 (если сменили название аромата баллона, то указываем только имя баллона для которого будет сброс учета, например Peony and juicy berries или Freshness of linen)
  - platform: template
    name: 'Counter reset: Peony and juicy berries' #Сбросить счетчик "Пион и сочные ягоды"
    icon: mdi:restart
    on_press:
      then:  
        - number.set:
            id: id_counter_aroma_ballon_01
            value: 0

#Сбросить счетчик для баллона 02 (если сменили название аромата баллона, то указываем только имя баллона для которого будет сброс учета, например Peony and juicy berries или Freshness of linen)
  - platform: template
    name: 'Counter reset: Freshness of linen' #Сбросить счетчик "Свежесть белья"
    icon: mdi:restart
    on_press:
      then:  
        - number.set:
            id: id_counter_aroma_ballon_02
            value: 0

#Сбросить счетчик для баллона 03 (если сменили название аромата баллона, то указываем только имя баллона для которого будет сброс учета, например Peony and juicy berries или Freshness of linen)
  - platform: template
    name: 'Counter reset: Ocean Oasis' #Сбросить счетчик "Океанский оазис"
    icon: mdi:restart
    on_press:
      then:  
        - number.set:
            id: id_counter_aroma_ballon_03
            value: 0

#Сбросить счетчик для баллона 04 (если сменили название аромата баллона, то указываем только имя баллона для которого будет сброс учета, например Peony and juicy berries или Freshness of linen)
  - platform: template
    name: 'Counter reset: Freshness of the morning' #Сбросить счетчик "Свежесть утра"
    icon: mdi:restart
    on_press:
      then:  
        - number.set:
            id: id_counter_aroma_ballon_04
            value: 0

#Сбросить счетчик для баллона 05 (если сменили название аромата баллона, то указываем только имя баллона для которого будет сброс учета, например Peony and juicy berries или Freshness of linen)
  - platform: template
    name: 'Counter reset: Japanese Garden' #Сбросить счетчик "Японский сад"
    icon: mdi:restart
    on_press:
      then:  
        - number.set:
            id: id_counter_aroma_ballon_05
            value: 0

#####################################################################################
################################### Текстовый сенсор ################################
text_sensor:
  - platform: template
    name: Ballon
    icon: mdi:spray
    id: ballon
    update_interval: 60s

  - platform: wifi_info
    ip_address:
      name: IP
#    ssid:
#      name: ${board_name} SSID
#    bssid:
#      name: ${board_name} BSSID
#    mac_address:
#      name: ${board_name} Mac
#    scan_results:
#      name: ${board_name} Latest_Scan_Results

#Время безотказной работы
  - platform: template
    name: Uptime ESP
    id: uptime_esp
    icon: mdi:clock-start
    entity_category: diagnostic

#####################################################################################
####################################### Время #######################################
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Moscow
```
